# Generated by Django 2.2.1 on 2019-05-26 04:38

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0015_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=30, verbose_name='手机')),
                ('birthday', models.CharField(max_length=30, verbose_name='生日')),
                ('city', models.CharField(max_length=40, verbose_name='城市')),
                ('website', models.URLField(max_length=40, verbose_name='个人主页')),
                ('school', models.CharField(max_length=40, verbose_name='学校')),
                ('major', models.CharField(max_length=40, verbose_name='专业')),
                ('skill', models.TextField(verbose_name='技能信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '简历信息',
                'verbose_name_plural': '简历信息',
            },
        ),
        migrations.CreateModel(
            name='EduInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_1', models.CharField(max_length=40, verbose_name='学校')),
                ('start_time_1', models.DateField(verbose_name='入学时间')),
                ('end_time_1', models.DateField(verbose_name='毕业时间')),
                ('school_2', models.CharField(max_length=40, null=True, verbose_name='学校')),
                ('start_time_2', models.DateField(null=True, verbose_name='入学时间')),
                ('end_time_2', models.DateField(null=True, verbose_name='毕业时间')),
                ('school_3', models.CharField(max_length=40, null=True, verbose_name='学校')),
                ('start_time_3', models.DateField(null=True, verbose_name='入学时间')),
                ('end_time_3', models.DateField(null=True, verbose_name='毕业时间')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ResumeData', verbose_name='简历')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
            },
        ),
    ]
